"use strict" //only one action gets user authentication status from /profile that is generated by passport look at authenticroutes.js for payload data
import axios from 'axios';
import {browserHistory} from 'react-router'; //need for redirecting user
export function getUser(){
  return function (dispatch){
    axios.get('/profile')
      .then(function(response){
          dispatch(
              {
                type:"GET_USER_STATUS",
                payload:response.data
              }
            )
        })
      .catch(function(err){
        dispatch({type:"GET_USER_STATUS_REJECTED",payload:err})
      })
    }
}

export function newUser(signupinfo){
  return function(){
    axios.post('/signup',signupinfo)
      .then(function(response){
        console.log("Is success")
        console.log(response.data)
      })
      .catch(function(err){
        console,log("Is error!")
      })
  }
}

export function checkUser(logininfo){
  return function(){
    axios.post('/login',logininfo)
      .then(function(response){
        console.log(response.data)
      })
      .catch(function(err){
        console,log(err)
      })
  }
}
