"use strict" //only one action gets user authentication status from /profile that is generated by passport look at authenticroutes.js for payload data
import axios from 'axios';

export function getUser(){
  return function (dispatch){
    axios.get('/profile')
      .then(function(response){
          dispatch(
              {
                type:"GET_USER_STATUS",
                payload:response.data
              }
            )
        })
      .catch(function(err){
        dispatch({type:"GET_USER_STATUS_REJECTED",payload:err})
      })
    }
}

export function newUser(signupinfo){
  return new Promise(function(resolve,reject){
    axios.post('/signup',signupinfo)
      .then(function(response){
        resolve(response.data)
      })
      .catch(function(err){
        reject(err)
      })
  })
}

export function checkUser(logininfo){
  return new Promise(function(resolve,reject){
    axios.post('/login',logininfo)
      .then(function(response){
        resolve(response.data)
      })
      .catch(function(err){
        reject(err)
      })
  })
}
